#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'arduino-ros2','console_scripts','pub_joycmd'
__requires__ = 'arduino-ros2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('arduino-ros2', 'console_scripts', 'pub_joycmd')()
    )
